localaddr = ":8789"
bearer = "grmbl"
#resolveraddr = "[::1]:7777"
resolveraddr = "127.0.0.1:7777"
resolvertimeout = "10m"
actiontimeout = "20s"
resolvernotfoundtimeout = "10s"
externaladdr = "https://localhost:8765"
loglevel = "DEBUG"

[grpcclient]
mediaserverdb = "localhost:7653"

[resttls]
type = "dev"

[server]
type = "dev"

[client]
type = "dev"

