#localaddr = ":8789"
localaddr = ":0"
bearer = "grmbl"
#resolveraddr = "[::1]:7777"
resolveraddr = "127.0.0.1:7777"
resolvertimeout = "10m"
actiontimeout = "15m"
resolvernotfoundtimeout = "10s"
externaladdr = "https://localhost:8765"

[grpcclient]
mediaserverdb = "localhost:7653"

[resttls]
type = "dev"

[server]
type = "dev"
interval = "3m"
usesystemcertpool = true

[client]
type = "dev"
interval = "3m"

[log]
level = "debug"

[log.stash]
#logstash_host="sb-uwf4.swissbib.unibas.ch"
logstashhost="localhost"
logstashport=5046
logstashtracelevel="ERROR"
namespace="mediaserveraction"
dataset=""
#dataset="logs-mediaserver"
[log.stash.tls]
type="file"
cert="certs/ub-log.ub.unibas.ch.cert.pem"
key="certs/ub-log.ub.unibas.ch.key.pem"
ca=["certs/ca.crt"]
interval="1h"
