#localaddr = ":8789"
localaddr = ":0"
#domains = ["ubmedia", "mediathek"]
domains = ["ubmedia"]
bearer = "grmbl"
#resolveraddr = "[::1]:7777"
resolveraddr = "127.0.0.1:7777"
resolvertimeout = "10m"
actiontimeout = "15m"
resolvernotfoundtimeout = "10s"
externaladdr = "https://localhost:8765"

#[grpcclient]
#mediaserverdb = "localhost:7653"

[resttls]
type = "minivault"
initialtimeout = "1h"
[resttls.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.2dc2b89922d3997b.652a813da024807d"
tokentype = "server_cert"
tokenpolicies = ["mediaserveraction"]
tokeninterval = "1h"
tokenttl = "2h"
certtype = "server_cert"
dnss = ["localhost"]
uris = []
ips = ["127.0.0.1", "::1"]
certinterval = "8m"
certttl = "10m"
ca = ["certs/minivault.ca.pem"]
usesystempool = false

[server]
type = "minivault"
initialtimeout = "1h"
[server.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.2dc2b89922d3997b.652a813da024807d" #pa.2dc483e73851c137.15d94e61e0b377f1
tokentype = "server_cert"
tokenpolicies = ["mediaserveraction"]
tokeninterval = "1h"
tokenttl = "2h"
certtype = "server_cert"
dnss = ["ubmedia.mediaserverproto.Action", "ubmedia.mediaserverproto.ActionDispatcher", "mediathek.mediaserverproto.Action", "mediathek.mediaserverproto.ActionDispatcher"]
uris = []
ips = []
certinterval = "8m"
certttl = "10m"
ca = ["certs/minivault.ca.pem"]
usesystempool = false


[client]
type = "minivault"
initialtimeout = "1h"
[client.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.2dc2b89922d3997b.652a813da024807d" #pa.2dc483e73851c137.15d94e61e0b377f1
tokentype = "client_cert"
tokenpolicies = ["mediaserveraction"]
tokeninterval = "2m"
tokenttl = "4m"
certtype = "client_cert"
dnss = []
uris = ["grpc:miniresolverproto.MiniResolver", "grpc:instance_ubimage.mediaserverproto.Action", "grpc:instance_ubviewer.mediaserverproto.Action", "grpc:ubmedia.mediaserverproto.Database", "grpc:mediathek.mediaserverproto.Database"]
ips = []
certinterval = "1m"
certttl = "30s"
ca = ["certs/minivault.ca.pem"]
usesystempool = false

[log]
level = "debug"

[log.stash]
#logstash_host="sb-uwf4.swissbib.unibas.ch"
logstashhost="localhost"
logstashport=5046
logstashtracelevel="ERROR"
namespace="miniresolver"
dataset=""
#dataset="logs-mediaserver"
[log.stash.tls]
type="file"
ca=["certs/ca.crt"]
interval="1h"
[log.stash.tls.file]
cert="certs/ub-log.ub.unibas.ch.cert.pem"
key="certs/ub-log.ub.unibas.ch.key.pem"
